// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Models;

namespace WebApi.Migrations
{
    [DbContext(typeof(ZamestnanciContext))]
    [Migration("20220421163844_testGetZam")]
    partial class testGetZam
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApi.Models.Archivovany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adresa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatumNarodenia")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumPrepustenia")
                        .HasColumnType("datetime2");

                    b.Property<string>("Meno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Plat")
                        .HasColumnType("real");

                    b.Property<string>("Pozicia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Priezvisko")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Archivovany");
                });

            modelBuilder.Entity("WebApi.Models.Pozicie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nazov")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pozicie");
                });

            modelBuilder.Entity("WebApi.Models.Predoslepozicie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DatumNastupu")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumUkoncenia")
                        .HasColumnType("datetime2");

                    b.Property<string>("Pozicia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("idZamestnanca")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Predoslepozicie");
                });

            modelBuilder.Entity("WebApi.Models.Zamestnanci", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adresa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatumNarodenia")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumNastupu")
                        .HasColumnType("datetime2");

                    b.Property<string>("Meno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Plat")
                        .HasColumnType("real");

                    b.Property<string>("Pozicia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Priezvisko")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Zamestnanci");
                });
#pragma warning restore 612, 618
        }
    }
}
